### ISSUE TITLE
cnpm装不了了

### ISSUE THREAD

**Issue by yuu2lee4** [N3-components/N3-components#14]
老是提示404

**Comment by x-cold** [comment]
这个大有可能是你的网络问题，检查一下源配置呗。
https://npm.taobao.org/package/N3-components，访问这个链接可以直接跳转到cnpm，里面有下载数据哦

**Comment by x-cold** [comment]
如果还存在问题的话，可以到我们的QQ交流群内讨论。
<a target="_blank" href="http://shang.qq.com/wpa/qunwpa?idkey=ae2b542ef32e8595664c746572d9a48187167e269ef5b6c80d8ed326fce5efdd"><img border="0" src="http://pub.idqqimg.com/wpa/images/group.png" alt="N3-components交流群" title="N3-components交流群"></a>
