### ISSUE TITLE
npm安装失败

### ISSUE THREAD

**Issue by AnzerWall** [N3-components/N3-components#19]
npm版本 3.10.8
node版本 6.4.0
系统版本 windows10

npm install N3-Components --save
安装失败，报告404

npm install n3-components --save
安装失败，报告404

npm install N3-components --save
安装成功。。。。

**Comment by x-cold** [comment]
非常抱歉，在文档里面提供的包名`N3-Components`，实际上我们在npm上发布时包名是`N3-components`，已更正文档。
