### ISSUE TITLE
Any plans for Vue 2.0 support?

### ISSUE THREAD

**Issue by sunabozu** [N3-components/N3-components#21]
Hi.

Vue 2.0 is almost here, are you going to support it any time soon?

**Comment by x-cold** [comment]
And we may not firstly update N3-components to suit for vue 2.
But, we are going to join or stage the project for building basic components of vue 2, which likes [http://react-component.github.io/badgeboard/](http://react-component.github.io/badgeboard/) and can be programming with any ui framework.

**Comment by yuu2lee4** [comment]
its a good idea
