### ISSUE TITLE
树的:checked-keys.sync的问题

### ISSUE THREAD

**Issue by chjw8016** [N3-components/N3-components#23]
树的:checked-keys.sync，当我通过事件改变选中数据时，页面上的选中效果并没有改变，这个是否也需要改一下。

**Comment by x-cold** [comment]
不好意思，由于家里有点事情。回复来晚了。请问你是怎么对`checked-keys`进行更新的，实际上在更新这个值的时候，是会进行视图的更新的。可以贴出更详细的代码吗？
