### ISSUE TITLE
layout中offset渲染后className没有布局模式

### ISSUE THREAD

**Issue by hebye3548** [N3-components/N3-components#29]
渲染后的class是n3-col-offset-x ， 没有布局模式md、xs……，样式无效。

**Comment by x-cold** [comment]
明天处理哦~

**Comment by x-cold** [comment]
你好，请提供一下版本号~。

我检查了一下源代码，是没有问题的，更新的[commit](https://github.com/N3-components/N3-components/commit/b169a042b1c2d5180c7ead6f62cdee59240d3a79)

_另外offset的值要保持是1-12的正整数。_

**Comment by hebye3548** [comment]
@x-cold 1.0.8
