### ISSUE TITLE
通过cooking构建项目，然后npm i的问题

### ISSUE THREAD

**Issue by dongshimou** [N3-components/N3-components#44]
我通过`cooking create project`
使用的是Vue2
然后 
`cd project`
`npm i N3-components`
然后检查并安装了依赖项。

main.js中如下
```
import Vue from 'vue';
import N3Components from 'N3-components';
import App from './app';

Vue.use(N3Components);

new Vue({ // eslint-disable-line
  el: '#app',
  render: h => h(App)
});
```

然而在 app.vue 中却无法使用N3的组件
比如 `<n3-button badge='2'>button</n3-button>`是无效的。
请问我哪儿出现了问题？

**Comment by dongshimou** [comment]
console的提示信息：
[Vue warn]: You are using the runtime-only build of Vue where the template option is not available. Either pre-compile the templates into render functions, or use the compiler-included build. 
(found in <N3Button>)

**Comment by zhangking** [comment]
你使用的是runtime-only的vue版本，建议使用完整版的vue
