### ISSUE TITLE
Open/Close Modal

### ISSUE THREAD

**Issue by zhongjixiuxing** [N3-components/N3-components#50]
在文档处没有给出怎样去open／Colse Modal, 我在查阅你的源码时才知道是采用open() 这样的函数方式来打开的；文档上给出的Global common modal说明； 亢了我去看源码～～；麻烦完善下文档，节省后来者的宝贵时间。thanks

**Comment by x-cold** [comment]
https://github.com/N3-components/N3-components/commit/dcb31de6445c97be8b15a99c947cc2bf7dfdc60b
