### ISSUE TITLE
electron-vue

### ISSUE THREAD

**Issue by cooltrooper** [N3-components/N3-components#54]
I have a blank installation of electorn-vue https://github.com/SimulatedGREG/electron-vue and have just installed n3 and when I come to use my first n3 component i get the following error:
`[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.`

**Comment by zhangking** [comment]
https://github.com/vuejs-templates/webpack/issues/215
