### ISSUE TITLE
Bug with Datepicker and custom format

### ISSUE THREAD

**Issue by sotaan** [N3-components/N3-components#55]
Hi,

There is a strange UI behavior when custom date format is setted. 
It seems like UI logic is still relying on `'MM-dd-yyyy'` format instead of using the custom one.
You can try on this [fiddle](https://jsfiddle.net/5k4ptmqg/32/) demonstrating the bug.

**Comment by zhangking** [comment]
thanks for your issues!  We have fixed it in v2.2.3
