### ISSUE TITLE
runtime-only build of Vue

### ISSUE THREAD

**Issue by elbarto132** [N3-components/N3-components#59]
Hi, i'm getting this error message as soon as i try to use any component of N3
> [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

application.js
```
import Vue from 'vue'
import N3Components from 'N3-components'
N3Components.install(Vue, 'en');
import App from './app.vue'

const app = new Vue({
  el: '#app-container',
  render: h => h(App)
});
```

app.vue
```
<template>
    <n3-button>button</n3-button>
</template>

<script>
    export default {

    }
</script>

```

**Comment by zhangking** [comment]
strange~  It must work if you used vue-loader.

**Comment by elbarto132** [comment]
I just had a further look at it. The problem only appears when i use it inside rails, if i create a new project using the vue-cli n3components is working es expected.
I'm using "rails new myapp --webpack=vue" to set up rails, webpacker and vue. If i use for example element ui inside this environment it's working, but n3components is not.
This rails/webpacker/vue setup is using vue-loader@12.2.1, same as the setup which is created by the vue-cli
I created an example project where you can see the error:
```
https://github.com/elbarto132/n3components_rails_problem
yarn install
./bin/webpack-dev-server
./bin/rails server
```

**Comment by sotaan** [comment]
I'm facing the same problem using egoist/vuepack project starter.
I had to put this in `resolve.alias`: 
```
 resolve: {
    extensions: ['.js', '.vue', '.css', '.json'],
    alias: {
      root: path.join(__dirname, '../client'),
       ....
      vue: 'vue/dist/vue.js'
      // or 
      // vue$: 'vue/dist/vue.esm.js'
    },
    modules: [
      ....
    ]
  },
```

Edit: maybe this can help: [vue-loader issue](https://github.com/vuejs/vue-loader/issues/560)

**Comment by x-cold** [comment]
Add vue template compiler in 0b02774
