### ISSUE TITLE
Select: case-insensitive search

### ISSUE THREAD

**Issue by anotheri** [N3-components/N3-components#63]
could you please provide case-insensitive search for `<n3-select search>` element, i believe that would improve UX a lot.

**Comment by anotheri** [comment]
it'd be as easy as add `i` to regexp here: 
https://github.com/N3-components/N3-components/blob/master/src/Select/n3Select.vue#L299

**Comment by zhangking** [comment]
OK,I will add a prop to control

**Comment by zhangking** [comment]
please check version 2.4.0
