### ISSUE TITLE
Better webpack configuration for improved integration in projects

### ISSUE THREAD

**Issue by sotaan** [N3-components/N3-components#67]
This webpack configuration is problematic mainly because dev and prod should have their own file for better integration in a project. 
For example, styles should be extracted in a css file in production mode.
I can show my configuration files as example if you want.

**Comment by x-cold** [comment]
I'd like to improve it from webpack 1 to webpack 2 / 3.
Meanwhile, we will separate different env.

**Comment by x-cold** [comment]
Now webpack 2.6 is in using by the branch of  '2.4.0'.

**Comment by zhangking** [comment]
please check version 2.4.0
