### ISSUE TITLE
Modal控件图标显示错误

### ISSUE THREAD

**Issue by hushang1228** [N3-components/N3-components#73]
应该显示一个绿色钩的‘success'图标没有显示，请帮看看是什么原因，谢谢！
截图中，Show Confirm按钮旁是一个测试用的n3-icon图标，单独显示正常，方法调用的n3Modal.confirm显示图标却不能正常解析n3-icon
```
  import Vue from 'vue'
  import N3Components from 'N3-components'

  Vue.use(N3Components)

  export default {
    name: 'app',
    methods: {
      showConfirm () {
        this.n3Modal.confirm({
          title: 'Title',
          message: 'This is a Modal。',
          effect: 'zoom',
          type: 'success',
          onShow () {
            console.log('open')
          },
          onConfirm () {
            console.log('confirm')
          },
          onHide () {
            console.log('hide')
          }
        })
      }
    }
  }
```

![image](https://user-images.githubusercontent.com/15414451/30049623-f39b1416-924d-11e7-99b5-6c5b62ab11fd.png)

**Comment by zhangking** [comment]
请提供完整的demo

**Comment by hushang1228** [comment]
包含node_module的完整demo，可直接运行(npm run dev)，请指教，谢谢！
[Uploading N3Test.zip…]()
如果文件不能正常下载，请查收邮件，已另发邮件中含有附件

**Comment by hushang1228** [comment]
这个bug出现在2.2.5，今天又重新下载了最新版本：2.4.2，已经没有这个问题了。
但main.js代码里需要引用这么一句:
import '../node_modules/N3-components/dist/index.min.css'
请版主确认一下，就是这么解决吗？如果是这样，那我稍后关闭这个bug.
谢谢！

**Comment by x-cold** [comment]
看起来应该是旧版的bug，具体还是要review一下code。
v2.4.0之后css文件已经分离出来了。
