### ISSUE TITLE
关于datepicker初始化的问题

### ISSUE THREAD

**Issue by jason5149** [N3-components/N3-components#74]
v-model绑定的数据如果为null，就会出现日期从1970开始，为undefined就不会，是故意的吗，我觉得如果是null也应该默认显示当前年份及月份
参考[fiddle](https://jsfiddle.net/jason5149/5k4ptmqg/94/)

**Comment by x-cold** [comment]
@zhangking

**Comment by x-cold** [comment]
Hi

```js
new Date(undefined)
Invalid Date

new Date(null)
Thu Jan 01 1970 08:00:00 GMT+0800 (CST)
```

**Comment by x-cold** [comment]
6d625a66eba4da99736fd852393318c0a0ba927d
