### ISSUE TITLE
N3-components  在安卓手机UC与QQ浏览器引用 出现白屏问题

### ISSUE THREAD

**Issue by ShareQiu1994** [N3-components/N3-components#79]
如题, 用全新的Vue-cli命令行安装Vue开发环境

在main.js中 加入
import N3Components from 'N3-components'
import 'N3-components/dist/index.min.css'
Vue.use(N3Components) 

后在 手机QQ与UC浏览器中测试 白屏~ 
苹果与PC端均正常

**Comment by x-cold** [comment]
我这边拿了一台安卓的机子测试都没有问题。
麻烦提供一下具体的机型、安卓版本、浏览器版本。

**Comment by ShareQiu1994** [comment]
测试环境为 安卓6.0.1， 机型 红米4 ， PC浏览器、QQ浏览器 测试出现此问题

**Comment by zhangking** [comment]
无法复现
