### ISSUE TITLE
支持npm安装和使用

### ISSUE THREAD

**Issue by ishenli** [N3-components/N3-components#9]
达到的效果

```
npm i N3-Components

// 安装完毕之后直接引用
import N3Components from 'N3-Components'

```

**Comment by yuu2lee4** [comment]
所以现在还不支持？

**Comment by zhangking** [comment]
很快就发布了

**Comment by ishenli** [comment]
good

发送自 Outlook Mobile

On Fri, Sep 9, 2016 at 7:31 PM +0800, "张凯" notifications@github.com wrote:

很快就发布了

**Comment by ligl** [comment]
东西不错，多久能npm安装呢

**Comment by x-cold** [comment]
已经发布npm包，链接如下： [https://www.npmjs.com/package/N3-components](https://www.npmjs.com/package/N3-components)，包名：N3-components。

Npm now is supported, access link is [https://www.npmjs.com/package/N3-components](https://www.npmjs.com/package/N3-components). Package Name: N3-components
